Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
